- hosts: localhost
  vars_prompt:
  - name: container_name
    prompt: "Enter docker container name: "
    private: no

  tasks:
  - name: "Configuring yum repository for docker"
    yum_repository:
      name: docker
      file: docker
      description: docker repo
      baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
      gpgcheck: no

  - name: "Install Docker-ce"
    package:
      name: "docker-ce-18.09.1-3.el7.x86_64"
      state: present

  - name: "start and enable docker service"
    service:
      name: "docker"
      state: started
      enabled: yes

  - name: "Installing Docker SDK for python3"
    command: "pip3 install docker-py"

  - name: "Pull docker image"
    docker_image:
      name: "hrishabhsharma/sshcentos:latest"
      source: pull

  - name: "Launching {{ container_name }} container"
    docker_container:
      name: "{{ container_name }}"
      image: "hrishabhsharma/sshcentos:latest"
      state: started
      interactive: yes
      detach: yes
      tty: yes

  - name: "Container info"
    docker_container_info:
      name: "{{ container_name }}"
    register: docker_info

  - debug:
      var: docker_info.container.NetworkSettings.IPAddress

  - name: "Retriving IP dynamically and updating in the inventory"
    template:
      src: "dockerip.txt"
      dest: "/root/ip.txt"

